name: Release Go Binaries

on:
  push:
    tags: ['v*']

jobs:
  release-go-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Go version
        run: echo "go-version=$(cat .go-version)" >> $GITHUB_ENV

      - name: Set up Go according to .go-version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}

      - name: Run GoReleaser according to .goreleaser.yml
        uses: goreleaser/goreleaser-action@v2
        with:
          workdir: app/
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
